# .github/workflows/ci.yml
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    # Map your GitHub secrets into job-level env vars
    env:
      AWS_REGION:     us-west-2
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      CODEBUILD_ROLE: ${{ secrets.CODEBUILD_ROLE }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Validate required secrets
        shell: bash
        run: |
          for var in AWS_ACCOUNT_ID CODEBUILD_ROLE ECR_REPOSITORY; do
            if [ -z "${!var}" ]; then
              echo "❌ Error: $var is not set"
              exit 1
            fi
          done

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region:    ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.CODEBUILD_ROLE }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Mask ECR password
        run: echo "::add-mask::${{ steps.login-ecr.outputs.password }}"
        

      - name: Build, tag & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./infra/docker/Dockerfile
          push:    true
          tags:    ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 neuroforge/

      - name: Run tests & collect coverage
        run: |
          pip install pytest coverage
          coverage run -m pytest tests/
          coverage xml -i

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml
