# .github/workflows/ci.yml
# Using GitHub Actions built-in coverage reporting (free alternative).
env:
  AWS_REGION: us-west-2
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}

name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Validate required secrets
        run: |
          for var in AWS_ACCOUNT_ID CODEBUILD_ROLE ECR_REPOSITORY; do
            if [ -z "${{ secrets["$var"] }}" ]; then
              echo "Error: secret $var is not set"
              exit 1
            fi
          done
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.CODEBUILD_ROLE }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint code
        run: |
          pip install flake8
          flake8 neuroforge/

      - name: Run tests and collect coverage
        run: |
          pip install pytest coverage
          coverage run -m pytest tests/
          coverage xml -i

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.xml